

POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "This is title4",
    "author": "This is author4",
    "url": "This is URL4",
    "likes": 400
}

###

DELETE http://localhost:3003/api/blogs/64f823308eb0e59692836c07

### 

PUT http://localhost:3003/api/blogs/64fee05acd6c6620fa3a7cf2
content-type : application/json

{
    "title": "This is title2",
    "author": "This is author2",
    "url": "This is URL2",
    "likes": 500
}

### 
POST http://localhost:3003/api/user
content-type: application/json

{
    "username":"prabinbastakoti",
    "name":"Prabin Bastakoti",
    "password":"acerswift3"
}


###
GET http://localhost:3003/api/user



### 
POST http://localhost:3001/api/login
content-type: application/json

{
    "username":"prabinbastakoti",
    "password":"acerswift3"
}


###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InByYWJpbmJhc3Rha290aSIsImlkIjoiNjRmYzJiYTlmOTkzYjdhOTNhMDgwNTUwIiwiaWF0IjoxNjk0MjQ3ODg1fQ.NDvc_bLvTA91RuHJTT6aIDHK_2fuxufN9JNDFAYcBzg

{
    "title":"single page app use token Authorization",
    "author":"Prabin Bastakoti",
    "url":"Url for blog",
    "likes":400
}

### 
DELETE http://localhost:3003/api/blogs/64fec392cd6c6620fa3a7cc0
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InByYWJpbmJhc3Rha290aSIsImlkIjoiNjRmYzJiYTlmOTkzYjdhOTNhMDgwNTUwIiwiaWF0IjoxNjk0MjQ3ODg1fQ.NDvc_bLvTA91RuHJTT6aIDHK_2fuxufN9JNDFAYcBzg


###
GET http://localhost:3001/api/blogs


###
POST http://localhost:3001/api/blogs/650dc2f290cf6f998b9aa16c/comment
content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InByYWJpbmJhc3Rha290aSIsImlkIjoiNjRmYzJiYTlmOTkzYjdhOTNhMDgwNTUwIiwiaWF0IjoxNjk1Mzk5NzAzfQ.LnlEf6HDb2kSrZCjUe0VY_V6otGSWsE2N1GpjfH6bNU

{
    "comment":"this is another comment"
}